### ISSUE TITLE
api access control

### ISSUE THREAD

**Issue by annsuparada** [better-professor-app/front-end#5]
Access to XMLHttpRequest at 'https://better-prof-app.herokuapp.com/api/professors/login' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

@kingmoc I'm getting this error. can you please help tomorrow?

**Comment by ShelbyDiamond** [comment]
resolved
